/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/base/BaseCheckbox.vue')['default']
    BaseRadio: typeof import('./components/base/BaseRadio.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    ConfirmDialog: typeof import('./components/feedback/ConfirmDialog.vue')['default']
    NotificationBar: typeof import('./components/feedback/NotificationBar.vue')['default']
  }
}
